name: Deploy Hugo Blog

# 当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: 构建网站
        run: hugo -D

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.token_sc }}
          EXTERNAL_REPOSITORY: https://ddyss.github.io/hugo-blog/
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
          commit_message: 🚀 Auto deploy from GitHub Actions
