name: Deploy Hugo Blog

# 当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 源码
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 安装 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.160.1"
          extended: true

      - name: 构建网站
        run: hugo -D --theme hugo-theme-stack

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.token_sc }}
          external_repository: ddyss/hugo-blog
          publish_branch: main
          publish_dir: ./public
          commit_message: 🚀 Auto deploy from GitHub Actions
